version: "3.1"
services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=actix
      - POSTGRES_USER=actix
      - POSTGRES_DB=actix
    restart: always

